/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[Name]
      ,[CatId]
      ,[Slug]
      ,[SupplierId]
      ,[Images]
      ,[ImageSecondary]
      ,[Detail]
      ,[Number]
      ,[Price]
      ,[PriceSale]
      ,[MetaDesc]
      ,[MetaKey]
      ,[CreatedBy]
      ,[CreatedAt]
      ,[UpdatedBy]
      ,[UpdatedAt]
      ,[SaleStart]
      ,[SaleEnd]
      ,[Status]
  FROM [ThietBiDienTu].[dbo].[Products]